services:
  # Full Stack Service (Frontend + Backend)
  - type: web
    name: kalasangam
    env: node
    plan: free
    buildCommand: cd client/kala-sangam && npm install && npm run build && cd ../../ && cp -r client/kala-sangam/dist ./ && cd server && npm install
    startCommand: cd server && node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://bolisettysamanvitha:XpFrzygY574FCLHf@cluster0.tohbv1j.mongodb.net/kalasangamdb?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 4d62b08c4f0532c4d8e2b81e0ecb087a7060d431bb12ff3a3d94c842cbbba249
      - key: JWT_EXPIRE
        value: 30d
      - key: BASE_URL_PROD
        value: https://kalasangam.onrender.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_EMAIL
        value: nefariamordeath@gmail.com
      - key: SMTP_PASSWORD
        value: qgyg jgsc qxxa wdoe
      - key: FROM_NAME
        value: KALASANGAM
      - key: FROM_EMAIL
        value: nefariamordeath@gmail.com
      - key: EVENTBRITE_TOKEN
        value: 2SJGH6KHAC74J6QOKKW3
