services:
  # Backend API Service
  - type: web
    name: kalasangam-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://bolisettysamanvitha:XpFrzygY574FCLHf@cluster0.tohbv1j.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 4d62b08c4f0532c4d8e2b81e0ecb087a7060d431bb12ff3a3d94c842cbbba249
      - key: JWT_EXPIRE
        value: 30d

  # Frontend Service
  - type: web
    name: kalasangam-frontend
    env: static
    plan: free
    rootDir: client/kala-sangam
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
